# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 10 Apr 2016 05:58:00 +0000
*               @ALL          0
*               @user         8
